### ISSUE TITLE
Scalable matrix profile

### ISSUE THREAD

**Issue by rtavenar** [tslearn-team/tslearn#260]
**Is your feature request related to a problem? Please describe.**
`tslearn` has a matrix profile module that relies on a naive implementation. Based on a discussion with @seanlaw in #126 we could maybe consider having STUMPY as an optional dependency for this matrixprofile module in order to benefit from their scalable implementations.

**Describe the solution you'd like**
That would require to improve on the existing `MatrixProfile` class by allowing to pick an implementation (using parameters passed at `__init__` time) and the `_transform(...)` method should call the correct function

One additional thing to check is how stumpy deals with:
* [x] variable-length time series
* [ ] multidimensional time series

I will probably not have time to work on it. If anyone is interested to give a hand on this, feel free to tell.

**Comment by seanlaw** [comment]
@rtavenar What is it meant by "variable-length time series"?

Regarding `multi-dimensional time series", STUMPY has support for this in the `stumpy.mstump` function (and with Dask (distributed server) support via `stumpy.mstumped` - note that functions ending with "ed" refer to Dask distributed support) but, with an increase in the number of dimensions, note that the computational cost will be higher.

**Comment by rtavenar** [comment]
> @rtavenar Can you clarify what is it meant by "variable-length time series"? Are you referring to streaming data?

What I mean is that in `tslearn`, we do not consider single time series but sets of time series. The question is whether STUMPY implementation would make it easy to deal with sets of time series in which all time series do not have the same number of timestamps.

**Comment by seanlaw** [comment]
> What I mean is that in tslearn, we do not consider single time series but sets of time series. The question is whether STUMPY implementation would make it easy to deal with sets of time series in which all time series do not have the same number of timestamps.

I'm not sure if this helps but, technically, STUMPY does not actually take "time" into account (i.e., there is no concept of time). In the dominant case, it just takes a NumPy array (or a vector in the 1-D case) of floating numbers, `T`, along with a window size, `m` and computes the matrix profile and matrix profile indices. So, you can analyze a 1D NumPy array of any length. For a set of time series, one would either compute the matrix profile for each time series independently OR one would concatenate the set into one long time series and then separate each time series with a single `np.nan` value. This latter "trick" allows you to discover motifs across multiple time series while making sure that time series boundaries (i.e., the end of `T1` and the beginning of `T2`) are ignored or not considered as a "relevant".

In the multi-dimensional case, it only makes sense that the data is "aligned" and have the same number of data points. Otherwise, the matrix profile analysis would make little sense but maybe I haven't thought about  it enough. 

Ultimately, is up to the user to pre-process their data for, say, missing data and to ensure that a multi-dimensional time series already has their data points aligned by "time". 

If that isn't clear then please feel free to ask more questions.

**Comment by tcrasset** [comment]
> Ultimately, is up to the user to pre-process their data for, say, missing data and to ensure that a multi-dimensional time series already has their data points aligned by "time".

I agree with this, I don't think it is the library's job to check for NaN values.

>  Based on a discussion with @seanlaw in #126 we could maybe consider having STUMPY as an optional dependency for this matrixprofile module in order to benefit from their scalable implementations.

In my opinion, this is the best way, there's no need for another matrix profile implementation at the moment, considering that STUMPY is specialized in this task. Moreover, this could free time for implementing algorithms that build on top of the matrix profile. As long as tslearn doesn't have algorithms to use the matrix profile with, using STUMPY as an optional dependency is the best bet in my opinion.

I am happy to give this a try, this will help me get familiar with tslearn!

**Comment by seanlaw** [comment]
> I agree with this, I don't think it is the library's job to check for NaN values.

For the record, STUMPY does currently "support" data that contains NaN/inf in the sense that it will not error out (since mean and stddev computations would typically have problems with those values) and gracefully set distances to `inf` for any subsequence that contains a NaN/inf.

> I am happy to give this a try, this will help me get familiar with tslearn!

@tcrasset Let me know if you have any questions about STUMPY

**Comment by seanlaw** [comment]
Btw, I noticed in the matrix profile user guide that there is a concept of a "segment". Does this mean that you will always have a segment that you are trying to search for amongst a set of time series? If that's the case, then this might be an easier problem to solve than when you don't know whether or not a pattern (or "repeating segment") even exists.

**Comment by tcrasset** [comment]
@seanlaw  Thanks, will do! I'm fairly new to all this, should I just ping you here if I have a question?

**Comment by seanlaw** [comment]
@tcrasset Yep, just @ me. I'm not familiar with tslearn inner workings but I can assist with the STUMPY bits

**Comment by rtavenar** [comment]
@tcrasset and I'll be there for the more `tslearn`-related stuff ;)

**Comment by rtavenar** [comment]
> Btw, I noticed in the matrix profile user guide that there is a concept of a "segment". Does this mean that you will always have a segment that you are trying to search for amongst a set of time series? If that's the case, then this might be an easier problem to solve than when you don't know whether or not a pattern (or "repeating segment") even exists.

No, what we do is the standard MP stuff described in your tutorial. I think @GillesVandewiele reported a segment for the purpose of illustration.

**Comment by GillesVandewiele** [comment]
Indeed, this "segment" notation is used to draw an analogy with our shapelet learning module as the distance calculation between shapelets and time series is very similar to how the matrix profile is constructed. But by pointing this out, I now acknowledge that this analogy could cause more confusion than being helpful so I might scratch that...

**Comment by tcrasset** [comment]
@rtavenar At the moment, in `matrix_profile.py` you process all the dimensions at once, by creating a `self.subsequence_length` x `d` sliding window if I understand correctly. Is that what you wish to do going forward? Should we only implement multi-dimensional matrix profile? And then it is the user's choice to input either 1 dimension at a time or all of them ?

I compared the output of STUMPY matrix profile and the tslearn one with the Trace data set, and they do not match in some places. 
I'll investigate this further.

Moreover, tslearn does not have the notion of matrix profile index but I guess that would not be too hard to add.
Do you want to completely scrap your implementation, or leave it be and add an option to use stumpy for the matrix profile computation?

I'll try to have a [WIP] pull-request by this evening.

**Comment by seanlaw** [comment]
@tcrasset Note that the a) multi-dimensional matrix profile output (and its calculation) for, say, `d` number of time series is fundamentally different from b) computing `d` individual matrix profiles. That is, a multi-dimensional matrix profile (computed via `stumpy.mstump` or `stumpy.mstumped`) is <b><u>not</u><b> equivalent to stacking 1-D matrix profiles on top of each other!

And then, depending on what you insights you are after, one might also c) concatenate the `d` time series (separated by an `np.nan`) and computing a single 1D matrix profile. Unlike computing the matrix profiles individually, for any given subsequence, this concatenation (separated by `np.nan`) allows you to find its nearest neighbor across <b>all</b> `d` time series. Whereas, in b), any given subsequence can only find a nearest neighbor within its own time series (i.e., subsequence `T1[i : i+m]` will only match another subsequence `T1[j : j+m]` within `T1`) 

For the purpose of speed and compatibility with `stumpy.stump` (or stumpy.stumped) and `stumpy.gpu_stump`, I'm guessing that you are actually mostly interested in scenarios b) and c). 

And for completeness:

1. `stumpy.stump`, `stumpy.stumped`, and `stumpy.gpu_stump` are all for 1D time series and should all generate the exact same output: an `np.ndarray` where the first column is the matrix profile values, the second column is the corresponding matrix profile indices (i.e., where is your nearest neighbor located), the third column is the corresponding "left" matrix profile indices (i.e., limited to relative index locations that are on your "left", where is your nearest left neighbor), and the fourth column is the corresponding "right" matrix profile indices (i.e., limited to relative index locations that are on your "right", where is your nearest right neighbor)
2. You may be confused about the difference between, say, `stumpy.stump` and `stumpy.stumped` (or `stumpy.mstump` and `stumpy.mstumped`). Any time you see a top level function ending in "ed", this implies that this function supports matrix profile computations across a distributed cluster of servers via `Dask distrbuted`. So, in all cases, since STUMPY is `Numba` JIT compiled, it will always try to use all of the CPUs on single server and compute matrix profiles in parallel. The Dask distributed versions simply take these computations and divides them up in an embarrassingly parallel fashion and spreads them across multiple servers (while also using all CPUs on each server).
3. Here is a [Google Colab notebook](https://tiny.cc/stumpy_colab) demonstrating how to use `stumpy.gpu_stump`. Aside from the function name, the function arguments are (purposely) nearly identical to `stumpy.stump`.

**Comment by rtavenar** [comment]
@seanlaw : Concerning the difference between a) and b), when I read https://stumpy.readthedocs.io/en/latest/api.html#stumpy.mstump I tend to understand that `stumpy.mstump` stacks 1d matrix profiles. Is it the doc that is misleading, or am I missing something.

Then, in `tslearn`, we assume that the dimensions are `(n_series, n_timestamps, n_features)` so I would assume that local distances on which MP rely are computed between multidimensional subseries of shape `(m, n_features)`.

Finally, if I understand, it would make sense to implement both intra-series and across-series MP. We could make that tunable as an __init__ parameter I guess.

**Comment by rtavenar** [comment]
@tcrasset maybe you can have a look at #261 to see if the fixes there are likely to make things better.
