### ISSUE TITLE
About piecewise method

### ISSUE THREAD

**Issue by NiuWenYu12138** [tslearn-team/tslearn#281]
I am new to this field,I was wondering if you could provide piecewise method for two-dimensional sequences.
So far my data is in two dimensions, but it doesn't work.
Many thanks!

**Comment by GillesVandewiele** [comment]
Hi there,

With those 2 dimensions. Do you mean that the first dimension is the number of timeseries and the second the length of the timeseries?

In order to convert these to 3 dimensions (which is required by tslearn) you can simply use [to_time_series_dataset](https://tslearn.readthedocs.io/en/stable/gen_modules/utils/tslearn.utils.to_time_series_dataset.html#tslearn.utils.to_time_series_dataset).

The [Getting Started](https://tslearn.readthedocs.io/en/stable/gettingstarted.html) page contains a handy tutorial.

**Comment by NiuWenYu12138** [comment]
Thank you so much for answering my question!
Best regard!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gilles Vandewiele"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 下午4:15
收件人: "tslearn-team/tslearn"<tslearn@noreply.github.com&gt;; 
抄送: "蜡笔小鑫"<2713627982@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tslearn-team/tslearn] About piecewise method (#281)





 
Hi there,
 
With those 2 dimensions. Do you mean that the first dimension is the number of timeseries and the second the length of the timeseries?
 
In order to convert these to 3 dimensions (which is required by tslearn) you can simply use to_time_series_dataset.
 
The Getting Started page contains a handy tutorial.

**Comment by GillesVandewiele** [comment]
Most welcome! If you have any further questions, feel free to create a new issue or to get in touch with us.
