### ISSUE TITLE
Not able to import "TimeSeriesKMeans" from "tslearn.clustering"

### ISSUE THREAD

**Issue by sanjaydeo1** [tslearn-team/tslearn#363]
When I am trying to **from tslearn.preprocessing import TimeSeriesScalerMeanVariance**  I am able to successfully import it. But when doing this **from tslearn.clustering import TimeSeriesKMeans** , I am getting **_SyntaxError: invalid syntax_**.

@rth rtavenar @ecederstrand  Please help with this. I am kind of stuck for a week. I am using data bricks notebook where I successfully installed tslearn package.

**Environment (please complete the following information):**
 - OS:Azure Databricks notebook
 - tslearn version 0.5.2

**Comment by ecederstrand** [comment]
I'm not a relearn maintainer, but it'll probably help the maintainers if you post the full stack trace.

**Comment by sanjaydeo1** [comment]
This is the output  for ****from tslearn.clustering import TimeSeriesKMeans** :** 
`Traceback (most recent call last):
  File "<command-4075763563396293>", line 5, in <module>
    from tslearn.clustering import TimeSeriesKMeans
  File "/databricks/python/local/lib/python2.7/site-packages/tslearn/clustering/__init__.py", line 8, in <module>
    from .kshape import KShape
  File "/databricks/python/local/lib/python2.7/site-packages/tslearn/clustering/kshape.py", line 178
    print("%.3f" % self.inertia_, end=" --> ")
                                     ^
SyntaxError: invalid syntax`

**Comment by GillesVandewiele** [comment]
tslearn is only supported for Python 3.6+. You are using Python 2.7

**Comment by sanjaydeo1** [comment]
Hey, @GillesVandewiele thanks for the answer. Now started using python3.5 and this is the error I got :

**Comment by madhuyadu** [comment]
This issue is still unresolved, I am facing this issue on databricks while executing the piece:
from tslearn.clustering import TimeSeriesKMeans
Error I get is: ImportError: numpy.core.multiarray failed to import
Error stack is as follows:

RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-1378707465225541> in <module>
      1 # import tslearn
----> 2 from tslearn.clustering import TimeSeriesKMeans #ImportError: numpy.core.multiarray failed to import
      3 from tslearn.preprocessing import TimeSeriesScalerMeanVariance

/databricks/python/lib/python3.7/site-packages/tslearn/clustering/__init__.py in <module>
      6  details.
      7 """
----> 8 from .kshape import KShape
      9 from .utils import (EmptyClusterError, silhouette_score,
     10                     TimeSeriesCentroidBasedClusteringMixin)

/databricks/python/lib/python3.7/site-packages/tslearn/clustering/kshape.py in <module>
      9 from tslearn.preprocessing import TimeSeriesScalerMeanVariance
     10 from tslearn.utils import to_time_series_dataset, check_dims
---> 11 from tslearn.metrics import cdist_normalized_cc, y_shifted_sbd_vec
     12 from tslearn.bases import BaseModelPackage, TimeSeriesBaseEstimator
     13 

/databricks/python/lib/python3.7/site-packages/tslearn/metrics/__init__.py in <module>
      6 further details.
      7 """
----> 8 from .dtw_variants import (dtw, dtw_limited_warping_length,
      9                            dtw_path_limited_warping_length, subsequence_path,
     10                            subsequence_cost_matrix,

/databricks/python/lib/python3.7/site-packages/tslearn/metrics/dtw_variants.py in <module>
      2 
      3 import numpy
----> 4 from numba import njit, prange
      5 from sklearn.metrics.pairwise import pairwise_distances
      6 

/databricks/python/lib/python3.7/site-packages/numba/__init__.py in <module>
     36 
     37 # Re-export decorators
---> 38 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
     39                                    jit_module)
     40 

/databricks/python/lib/python3.7/site-packages/numba/core/decorators.py in <module>
     10 
     11 from numba.core.errors import DeprecationError, NumbaDeprecationWarning
---> 12 from numba.stencils.stencil import stencil
     13 from numba.core import config, extending, sigutils, registry
     14 

/databricks/python/lib/python3.7/site-packages/numba/stencils/stencil.py in <module>
      9 from llvmlite import ir as lir
     10 
---> 11 from numba.core import types, typing, utils, ir, config, ir_utils, registry
     12 from numba.core.typing.templates import (CallableTemplate, signature,
     13                                          infer_global, AbstractTemplate)

/databricks/python/lib/python3.7/site-packages/numba/core/ir_utils.py in <module>
     14 
     15 import numba
---> 16 from numba.core.extending import _Intrinsic
     17 from numba.core import types, utils, typing, ir, analysis, postproc, rewrites, config, cgutils
     18 from numba.core.typing.templates import (signature, infer_global,

/databricks/python/lib/python3.7/site-packages/numba/core/extending.py in <module>
     17 from numba.core.datamodel import models   # noqa: F401
     18 from numba.core.datamodel import register_default as register_model  # noqa: F401, E501
---> 19 from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
     20 from numba._helperlib import _import_cython_function  # noqa: F401
     21 from numba.core.serialize import ReduceMixin

/databricks/python/lib/python3.7/site-packages/numba/core/pythonapi.py in <module>
     10 
     11 import ctypes
---> 12 from numba import _helperlib
     13 from numba.core import (
     14     types, utils, config, lowering, cgutils, imputils, serialize,

ImportError: numpy.core.multiarray failed to import
